### ISSUE TITLE
LCD4linux r7

### ISSUE THREAD

**Issue by GWARDAR** [eriksl/enigma2-plugin-extensions-lcd4linux-ihad-source-copy#4]
eriksl hello LCD4linux r7 plugin released new version please update it for OpenPLi

**Comment by eriksl** [comment]
What does it feature against the version we're now supplying. It's quite a bit of work to incorporate it, so I won't do it if there is little or no improvement.

**Comment by GWARDAR** [comment]
r7 (14.06.) : MP: +Progamminfo; OWM: neue API für kostenfreie Key-Nutzung; Netatmo: +Batteriewarnung (gelb)
r7 (14.06.): MP: + program info; OWM: new API for free key use; Netatmo: + battery warning (yellow)
This was written in the update by the Author of the plugin.
ps do not be offended by me! I used to think that the most difficult thing is to write a completely new image, but I could not imagine for myself that changing a plug-in is a big crap, most likely I don’t understand anything about it. But thanks to you all for responding to my request! Some people are generally silent and do not answer my requests.
